# docker/docker-compose.yml
version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: docker/api/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=false
    depends_on:
      - model-server

  model-server:
    build:
      context: .
      dockerfile: docker/model_server/Dockerfile
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - ./models:/app/models